### ISSUE TITLE
Post here information about the datasets

### ISSUE THREAD

**Issue by Lagrang3** [Brugui7/HashCode21#1]
1. we need to know the max number of ingredients.
2. plot a histogram of pizzas according to their number of ingredients
3. plot a histogram of teams according to the number of people
4. plot a histogram of ingredients according to number of pizzas in which it is present
5. maximum size of pizza

**Comment by Kaomab** [comment]
Fog guy It if h N G o ooh h  get g ![image](https://github.com/Brugui7/HashCode21/assets/89643639/328caddc-87c5-4823-9041-0e19e8af65f4)
